services:
  tomcat:
    build: .
    container_name: "${COMPOSE_PROJECT_NAME}_tomcat"
    environment:
      DB_RESOURCE_NAME: 'jdbc/helloworld'
      DB_URL: 'jdbc:postgresql://postgres-1.localdomain/helloworld'
      DB_USERNAME: 'user'
      DB_PASSWORD_FILE: 'secrets/db-password'
      DB_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
      MANAGER_PASSWORD_FILE: 'secrets/manager-password'
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  # Mapeia o diretório src do host para o contêiner
      - ./target:/app/target  # Mapeia o diretório target do contêiner para o host
#      - ./dependency/postgresql-42.2.5.jar:/usr/local/tomcat/lib/postgresql-42.2.5.jar:ro
#      - ./webapps/hello-servlet.war:/usr/local/tomcat/webapps/hello-servlet.war:ro
      - ./secrets/manager-password:/usr/local/tomcat/secrets/manager-password:ro
      - ./secrets/db-password:/usr/local/tomcat/secrets/db-password:ro
      - ./logs:/usr/local/tomcat/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
